import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable"; // Explicitly import autoTable

// Logo placeholder - in real case would be base64 image
const EVOQUE_LOGO_BASE64 = "";

export async function generateWeeklyReportPDF(data: any) {
    const doc = new jsPDF(); // No longer need to cast to any here, autoTable will be called directly

    // 1. Header & Logo
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(79, 70, 229); // Indigo-600
    doc.text("EVOQUE | ENGAGE", 14, 22);

    doc.setFontSize(12);
    doc.setTextColor(100, 116, 139);
    doc.text("Weekly Retention Intelligence Report", 14, 30);
    doc.text(`Period: ${data.periodo}`, 140, 30, { align: "right" });

    doc.setDrawColor(79, 70, 229);
    doc.setLineWidth(0.5);
    doc.line(14, 35, 196, 35);

    // 2. Executive Summary
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Resumo Executivo", 14, 50);

    autoTable(doc, { // Changed from doc.autoTable to autoTable(doc, ...)
        startY: 55,
        theme: 'grid',
        headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255] },
        body: [
            ["Alunos em Risco (Faixa Vermelha)", data.total_red, `${data.diff_value} vs Prev.`],
            ["Taxa de Resgate (Eficiência)", `${data.recovery_rate}%`, `${data.recovered_count} Alunos`],
            ["ROI de Retenção Estimado", `R$ ${data.roi.toLocaleString('pt-BR')}`, "Impacto Financeiro"]
        ]
    });

    // 3. Hedonic Analysis
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Análise de Prazer (Hedônica)", 14, (doc as any).lastAutoTable.finalY + 20);

    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139);
    doc.text(`Média de Prazer no Treino da Unidade: ${data.hedonic_avg}/10.0`, 14, (doc as any).lastAutoTable.finalY + 28);

    // 4. Call List Table
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Lista de Chamada: Intervenção Prioritária", 14, (doc as any).lastAutoTable.finalY + 45);

    autoTable(doc, { // Changed from doc.autoTable to autoTable(doc, ...)
        startY: (doc as any).lastAutoTable.finalY + 50,
        theme: 'striped',
        head: [['Aluno', 'EvoID', 'Último Treino', 'Status']],
        body: data.target_students.map((s: any) => [
            s.name,
            s.evoId,
            s.last_training,
            { content: 'Sem Resposta', styles: { textColor: [239, 68, 68], fontStyle: 'bold' } }
        ]),
        headStyles: { fillColor: [30, 41, 59] }
    });

    // 5. Footer
    const finalY = (doc as any).lastAutoTable.finalY || 200;
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by Engage Analysis Engine on ${data.date_generated}`, 14, 285);
    doc.text("Evoque Academias - CONFIDENCIAL", 196, 285, { align: "right" });

    return doc.output("arraybuffer");
}
